### ISSUE TITLE
 Cannot find module 'ionic-color-picker'.

### ISSUE THREAD

**Issue by haakon-io** [KokilaBawankar/ionic-color-picker#1]
Tried to use your color picker but I can't seem to import it. Using Angular 8 and Ionic.

Regards

**Comment by supermafete** [comment]
Same here. It seems there isn't any file or export.

**Comment by sapabg** [comment]
+1

**Comment by alainm23** [comment]
+1

**Comment by dberniell** [comment]
+1

**Comment by dartrox21** [comment]
+1

**Comment by fchristl** [comment]
Same problem. If I see it correctly, the issue is that `package.json` links to `dist/index.js`, but the code is compiled to `dist/out-tsc/...`.

**Comment by KokilaBawankar** [comment]
Issue is solved now, remove the old version and install the latest 1.0.0 version. Now I am closing this issue.
